### ISSUE TITLE
Adding multiple pieces of metadata to a RodsItem by passing a Tuple fails

### ISSUE THREAD

**Issue by mksanger** [wtsi-npg/partisan#46]
```
>>> obj.add_metadata((AVU("a", "b"), AVU("1", "2")))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mk35/python/lib/python3.10/site-packages/partisan/irods.py", line 1059, in wrapper
    return method(*args, **kwargs)
  File "/Users/mk35/python/lib/python3.10/site-packages/partisan/irods.py", line 1128, in add_metadata
    c.add_metadata(item, timeout=timeout, tries=tries)
  File "/Users/mk35/python/lib/python3.10/site-packages/partisan/irods.py", line 266, in add_metadata
    self._execute(
  File "/Users/mk35/python/lib/python3.10/site-packages/partisan/irods.py", line 489, in _execute
    return self._unwrap(response)
  File "/Users/mk35/python/lib/python3.10/site-packages/partisan/irods.py", line 512, in _unwrap
    raise RodsError(err[Baton.MSG], err[Baton.CODE])
partisan.exception.RodsError: <RodsError: Invalid AVU: not a JSON object code: -816000>
```

The type hint for `RodsItem.addmetadata()` at https://github.com/wtsi-npg/partisan/blob/c69369ac5b47854c18f4d2f56ea6c4eee4aecb3e/src/partisan/irods.py#L1109 suggests that this use should be possible

**Comment by kjsanger** [comment]
It _is_ possible. The type hint is still wrong, though; I think it should be `tuple[AVU, ...]` (see https://docs.python.org/3/library/typing.html#typing.Tuple)

You're passing a single tuple of AVUs, while the function signature is variadic. The unit tests check support for >1 AVU here https://github.com/wtsi-npg/partisan/blob/c69369ac5b47854c18f4d2f56ea6c4eee4aecb3e/tests/test_irods.py#L317
